services:
  - type: web
    name: greenhouse-monitor
    env: python
    buildCommand: pip install -r IOT_Webapp/requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENWEATHER_API_KEY
        sync: false
